worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /run/nginx.pid;


events {
    worker_connections  2048;
}

http {
    upstream srh_backend {
        server 05-redis-sentinel-camellia-srh-srh-1:80;
        server 05-redis-sentinel-camellia-srh-srh-2:80;
        server 05-redis-sentinel-camellia-srh-srh-3:80;
        server 05-redis-sentinel-camellia-srh-srh-4:80;
        server 05-redis-sentinel-camellia-srh-srh-5:80;
        server 05-redis-sentinel-camellia-srh-srh-6:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://srh_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
